[package]
name = "repro"
version = "0.0.0"

[lib]
path = "nonexistent.rs"
proc-macro = true

# Run any bazel command with `CARGO_BAZEL_REPIN=1`
[dependencies]
gdal = { version = "0.15.0", features = ["array"] }
gdal-sys = "0.9.0"
